# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER_DEV'] %>
  password: <%= ENV['POSTGRES_PASSWORD_DEV'] %>
  host: host.docker.internal
  # host: database
  port: 5432

development:
  <<: *default
  database: <%= ENV['POSTGRES_DATABASE_DEV'] %>

test:
  <<: *default
  database: <%= ENV['POSTGRES_DATABASE_TEST'] %>

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV['POSTGRES_DATABASE_PROD'] %>
    username: <%= ENV['POSTGRES_USER_DEV'] %>
    password: <%= ENV['POSTGRES_PASSWORD_DEV'] %>
  cache:
    <<: *primary_production
    database: <%= ENV['POSTGRES_DATABASE_PROD'] %>_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: <%= ENV['POSTGRES_DATABASE_PROD'] %>_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: <%= ENV['POSTGRES_DATABASE_PROD'] %>_cable
    migrations_paths: db/cable_migrate
